#!/bin/bash

set -e

if [[ -n "${RF_DEBUG}" ]]; then
    set -x
fi

function usage() {
    echo -n \
"Usage: $(basename "$0")

Attempts to setup the project's development environment.
"
}

if [ "${BASH_SOURCE[0]}" = "${0}" ]; then
    if [ "${1:-}" = "--help" ]; then
        usage
    else
        # This prevents a container build failure when copying 
        # the nginx/srv/dist/ directory before it exists.
        # https://github.com/raster-foundry/raster-foundry/pull/3800
        mkdir -p "nginx/srv/dist/"

        vagrant up --provision
    fi
fi
